name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    uses: crawlora-com/starter-apps/.github/workflows/publish.yaml@main
    secrets:
      auth_key: ${{ env.CRAWLORA_AUTH_KEY }}
